function registerEnrollOrg() {

  local ORGNAMEINSMALL=$1
  local CAPORT=$2
  local CAPORT2=$3

  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:${CAPORT} --caname ca-${ORGNAMEINSMALL} --tls.certfiles "${PWD}/organizations/fabric-ca/${ORGNAMEINSMALL}/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-${CAPORT}-ca-${ORGNAMEINSMALL}.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-${CAPORT}-ca-${ORGNAMEINSMALL}.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-${CAPORT}-ca-${ORGNAMEINSMALL}.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-${CAPORT}-ca-${ORGNAMEINSMALL}.pem
    OrganizationalUnitIdentifier: orderer" >"${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy ${ORGNAMEINSMALL}'s CA cert to ${ORGNAMEINSMALL}'s /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/${ORGNAMEINSMALL}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/msp/tlscacerts/ca.crt"

  # Copy ${ORGNAMEINSMALL}'s CA cert to ${ORGNAMEINSMALL}'s /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/${ORGNAMEINSMALL}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/tlsca/tlsca.${ORGNAMEINSMALL}.example.com-cert.pem"

  # Copy ${ORGNAMEINSMALL}'s CA cert to ${ORGNAMEINSMALL}'s /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/${ORGNAMEINSMALL}/ca-cert.pem" "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/ca/ca.${ORGNAMEINSMALL}.example.com-cert.pem"

  # ------------------------------------------------ X -------------------------------------------------------- #

  # Registering Peer 0
  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-${ORGNAMEINSMALL} --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/${ORGNAMEINSMALL}/ca-cert.pem"
  { set +x; } 2>/dev/null

  # ------------------------------------------------ X -------------------------------------------------------- #

  # echo "Registering user"
  # set -x
  # fabric-ca-client register --caname ca-${ORGNAMEINSMALL} --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/${ORGNAMEINSMALL}/ca-cert.pem"
  # { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-${ORGNAMEINSMALL} --id.name ${ORGNAMEINSMALL}admin --id.secret ${ORGNAMEINSMALL}adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/${ORGNAMEINSMALL}/ca-cert.pem"
  { set +x; } 2>/dev/null

  # ------------------------------------------------ X -------------------------------------------------------- #

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:${CAPORT} --caname ca-${ORGNAMEINSMALL} -M "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/peers/peer0.${ORGNAMEINSMALL}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/${ORGNAMEINSMALL}/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/peers/peer0.${ORGNAMEINSMALL}.example.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:${CAPORT} --caname ca-${ORGNAMEINSMALL} -M "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/peers/peer0.${ORGNAMEINSMALL}.example.com/tls" --enrollment.profile tls --csr.hosts peer0.${ORGNAMEINSMALL}.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/${ORGNAMEINSMALL}/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/peers/peer0.${ORGNAMEINSMALL}.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/peers/peer0.${ORGNAMEINSMALL}.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/peers/peer0.${ORGNAMEINSMALL}.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/peers/peer0.${ORGNAMEINSMALL}.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/peers/peer0.${ORGNAMEINSMALL}.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/peers/peer0.${ORGNAMEINSMALL}.example.com/tls/server.key"

  # ------------------------------------------------ X -------------------------------------------------------- #

  # echo "Generating the user msp"
  # set -x
  # fabric-ca-client enroll -u https://user1:user1pw@localhost:${CAPORT} --caname ca-${ORGNAMEINSMALL} -M "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/users/User1@${ORGNAMEINSMALL}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/${ORGNAMEINSMALL}/ca-cert.pem"
  # { set +x; } 2>/dev/null

  # cp "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/users/User1@${ORGNAMEINSMALL}.example.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://${ORGNAMEINSMALL}admin:${ORGNAMEINSMALL}adminpw@localhost:${CAPORT} --caname ca-${ORGNAMEINSMALL} -M "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/users/Admin@${ORGNAMEINSMALL}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/${ORGNAMEINSMALL}/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/${ORGNAMEINSMALL}.example.com/users/Admin@${ORGNAMEINSMALL}.example.com/msp/config.yaml"
}
