import type { TVoter } from "../types/VoterTypes";

export const voterListData: TVoter[] = [
  {
    _id: "a1f92c",
    voterId: "VOTER0001",
    voterName: "Shah Md. Rafiul Kadir",
    dateOfBirth: "1999-05-14",
    constituency: {
      divisionName: "Dhaka",
      districtName: "Dhaka",
      constituencyNumber: 2,
      constituencyName: "Dhaka-2",
      homeAddress: "house #21, road #2, latif real estate, mohammadpur, dhaka",
      cityCorporation: {
        cityCorporationName: "Dhaka South City Corporation",
        wardNumber: 10,
      },
    },
  },
  {
    _id: "b2d81a",
    voterId: "VOTER0002",
    voterName: "Farhana Akter",
    dateOfBirth: "1997-03-12",
    constituency: {
      divisionName: "dhaka",
      districtName: "dhaka",
      constituencyNumber: 75,
      constituencyName: "dhaka-2",
      homeAddress: "block c, mirpur-2, dhaka",
      cityCorporation: {
        cityCorporationName: "DNCC North",
        wardNumber: 12,
      },
    },
  },
  {
    _id: "c3e72b",
    voterId: "VOTER0003",
    voterName: "Md. Hasan Ali",
    dateOfBirth: "1988-11-20",
    constituency: {
      divisionName: "chattogram",
      districtName: "chattogram",
      constituencyNumber: 15,
      constituencyName: "chattogram-7",
      homeAddress: "pahartali, chattogram",
      cityCorporation: {
        cityCorporationName: "Chattogram City Corporation",
        wardNumber: 19,
      },
    },
  },
  {
    _id: "d4f63c",
    voterId: "VOTER0004",
    voterName: "Nusrat Jahan",
    dateOfBirth: "1995-09-08",
    constituency: {
      divisionName: "rajshahi",
      districtName: "bogura",
      constituencyNumber: 42,
      constituencyName: "bogura-3",
      homeAddress: "shibganj, bogura",
      upazila: {
        upazilaName: "shibganj",
        unionName: "shibganj union",
        wardNumber: 4,
      },
    },
  },
  {
    _id: "e5a74d",
    voterId: "VOTER0005",
    voterName: "Abdul Karim",
    dateOfBirth: "1976-06-18",
    constituency: {
      divisionName: "sylhet",
      districtName: "sylhet",
      constituencyNumber: 22,
      constituencyName: "sylhet-4",
      homeAddress: "beanibazar, sylhet",
      upazila: {
        upazilaName: "beanibazar",
        unionName: "beanibazar union",
        wardNumber: 2,
      },
    },
  },
  {
    _id: "f6b85e",
    voterId: "VOTER0006",
    voterName: "Tania Sultana",
    dateOfBirth: "1993-01-25",
    constituency: {
      divisionName: "khulna",
      districtName: "khulna",
      constituencyNumber: 90,
      constituencyName: "khulna-2",
      homeAddress: "sonadanga residential area, khulna",
      cityCorporation: {
        cityCorporationName: "Khulna City Corporation",
        wardNumber: 9,
      },
    },
  },
  {
    _id: "g7c96f",
    voterId: "VOTER0007",
    voterName: "Md. Saiful Islam",
    dateOfBirth: "1990-07-14",
    constituency: {
      divisionName: "mymensingh",
      districtName: "mymensingh",
      constituencyNumber: 144,
      constituencyName: "mymensingh-6",
      homeAddress: "phulpur, mymensingh",
      upazila: {
        upazilaName: "phulpur",
        unionName: "phulpur union",
        wardNumber: 6,
      },
    },
  },
  {
    _id: "h8d07g",
    voterId: "VOTER0008",
    voterName: "Shamima Ferdous",
    dateOfBirth: "1992-04-02",
    constituency: {
      divisionName: "barisal",
      districtName: "barisal",
      constituencyNumber: 120,
      constituencyName: "barisal-1",
      homeAddress: "chawk bazar, barisal",
      cityCorporation: {
        cityCorporationName: "Barisal City Corporation",
        wardNumber: 3,
      },
    },
  },
  {
    _id: "i9e18h",
    voterId: "VOTER0009",
    voterName: "Kamal Hossain",
    dateOfBirth: "1982-12-30",
    constituency: {
      divisionName: "dhaka",
      districtName: "gazipur",
      constituencyNumber: 78,
      constituencyName: "gazipur-1",
      homeAddress: "tongi, gazipur",
      cityCorporation: {
        cityCorporationName: "Gazipur City Corporation",
        wardNumber: 18,
      },
    },
  },
  {
    _id: "j0f29i",
    voterId: "VOTER0010",
    voterName: "Mitu Akhter",
    dateOfBirth: "1998-08-19",
    constituency: {
      divisionName: "rangpur",
      districtName: "rangpur",
      constituencyNumber: 130,
      constituencyName: "rangpur-3",
      homeAddress: "pirgacha, rangpur",
      upazila: {
        upazilaName: "pirgacha",
        unionName: "pirgacha union",
        wardNumber: 1,
      },
    },
  },
  // ---- Adding 20 more voters ----
  {
    _id: "k1g30j",
    voterId: "VOTER0011",
    voterName: "Nurul Amin",
    dateOfBirth: "1975-05-01",
    constituency: {
      divisionName: "rajshahi",
      districtName: "rajshahi",
      constituencyNumber: 50,
      constituencyName: "rajshahi-4",
      homeAddress: "motihar, rajshahi",
      cityCorporation: {
        cityCorporationName: "Rajshahi City Corporation",
        wardNumber: 7,
      },
    },
  },
  {
    _id: "l2h41k",
    voterId: "VOTER0012",
    voterName: "Jannatul Mawa",
    dateOfBirth: "2000-02-12",
    constituency: {
      divisionName: "dhaka",
      districtName: "narayanganj",
      constituencyNumber: 82,
      constituencyName: "narayanganj-2",
      homeAddress: "fatullah, narayanganj",
      cityCorporation: {
        cityCorporationName: "Narayanganj City Corporation",
        wardNumber: 10,
      },
    },
  },
  {
    _id: "m3i52l",
    voterId: "VOTER0013",
    voterName: "Shafiqul Islam",
    dateOfBirth: "1991-10-09",
    constituency: {
      divisionName: "sylhet",
      districtName: "moulvibazar",
      constituencyNumber: 24,
      constituencyName: "moulvibazar-2",
      homeAddress: "kulaura, moulvibazar",
      upazila: {
        upazilaName: "kulaura",
        unionName: "kulaura union",
        wardNumber: 5,
      },
    },
  },
  {
    _id: "n4j63m",
    voterId: "VOTER0014",
    voterName: "Momena Khatun",
    dateOfBirth: "1989-11-27",
    constituency: {
      divisionName: "khulna",
      districtName: "jessore",
      constituencyNumber: 93,
      constituencyName: "jessore-3",
      homeAddress: "jhikargacha, jessore",
      upazila: {
        upazilaName: "jhikargacha",
        unionName: "jhikargacha union",
        wardNumber: 3,
      },
    },
  },
  {
    _id: "o5k74n",
    voterId: "VOTER0015",
    voterName: "Asif Mahmud",
    dateOfBirth: "1996-06-15",
    constituency: {
      divisionName: "dhaka",
      districtName: "dhaka",
      constituencyNumber: 76,
      constituencyName: "dhaka-3",
      homeAddress: "jatrabari, dhaka",
      cityCorporation: {
        cityCorporationName: "DSCC South",
        wardNumber: 28,
      },
    },
  },
  {
    _id: "p6l85o",
    voterId: "VOTER0016",
    voterName: "Parveen Sultana",
    dateOfBirth: "1984-09-03",
    constituency: {
      divisionName: "mymensingh",
      districtName: "jamalpur",
      constituencyNumber: 147,
      constituencyName: "jamalpur-3",
      homeAddress: "melandaha, jamalpur",
      upazila: {
        upazilaName: "melandaha",
        unionName: "melandaha union",
        wardNumber: 8,
      },
    },
  },
  {
    _id: "q7m96p",
    voterId: "VOTER0017",
    voterName: "Khadija Begum",
    dateOfBirth: "1994-12-11",
    constituency: {
      divisionName: "rangpur",
      districtName: "dinajpur",
      constituencyNumber: 135,
      constituencyName: "dinajpur-2",
      homeAddress: "birampur, dinajpur",
      upazila: {
        upazilaName: "birampur",
        unionName: "birampur union",
        wardNumber: 7,
      },
    },
  },
  {
    _id: "r8n07q",
    voterId: "VOTER0018",
    voterName: "Rubel Hossain",
    dateOfBirth: "1992-02-20",
    constituency: {
      divisionName: "barisal",
      districtName: "patuakhali",
      constituencyNumber: 124,
      constituencyName: "patuakhali-2",
      homeAddress: "galachipa, patuakhali",
      upazila: {
        upazilaName: "galachipa",
        unionName: "galachipa union",
        wardNumber: 2,
      },
    },
  },
  {
    _id: "s9o18r",
    voterId: "VOTER0019",
    voterName: "Shahidul Islam",
    dateOfBirth: "1990-03-22",
    constituency: {
      divisionName: "chattogram",
      districtName: "cox's bazar",
      constituencyNumber: 19,
      constituencyName: "cox's bazar-2",
      homeAddress: "teknaf, cox's bazar",
      upazila: {
        upazilaName: "teknaf",
        unionName: "teknaf union",
        wardNumber: 6,
      },
    },
  },
  {
    _id: "t0p29s",
    voterId: "VOTER0020",
    voterName: "Mahmudul Hasan",
    dateOfBirth: "1997-07-07",
    constituency: {
      divisionName: "dhaka",
      districtName: "manikganj",
      constituencyNumber: 85,
      constituencyName: "manikganj-2",
      homeAddress: "saturia, manikganj",
      upazila: {
        upazilaName: "saturia",
        unionName: "saturia union",
        wardNumber: 4,
      },
    },
  },
  {
    _id: "u1q30t",
    voterId: "VOTER0021",
    voterName: "Shamim Ahmed",
    dateOfBirth: "1985-10-10",
    constituency: {
      divisionName: "dhaka",
      districtName: "dhaka",
      constituencyNumber: 79,
      constituencyName: "dhaka-6",
      homeAddress: "dhanmondi, dhaka",
      cityCorporation: {
        cityCorporationName: "DSCC South",
        wardNumber: 15,
      },
    },
  },
  {
    _id: "v2r41u",
    voterId: "VOTER0022",
    voterName: "Firoza Khatun",
    dateOfBirth: "1999-01-29",
    constituency: {
      divisionName: "rajshahi",
      districtName: "naogaon",
      constituencyNumber: 48,
      constituencyName: "naogaon-5",
      homeAddress: "atri, naogaon",
      upazila: {
        upazilaName: "atri",
        unionName: "atri union",
        wardNumber: 9,
      },
    },
  },
  {
    _id: "w3s52v",
    voterId: "VOTER0023",
    voterName: "Rakibul Hasan",
    dateOfBirth: "1993-04-14",
    constituency: {
      divisionName: "chattogram",
      districtName: "feni",
      constituencyNumber: 13,
      constituencyName: "feni-1",
      homeAddress: "parshuram, feni",
      upazila: {
        upazilaName: "parshuram",
        unionName: "parshuram union",
        wardNumber: 3,
      },
    },
  },
  {
    _id: "x4t63w",
    voterId: "VOTER0024",
    voterName: "Monira Begum",
    dateOfBirth: "1987-08-18",
    constituency: {
      divisionName: "sylhet",
      districtName: "habiganj",
      constituencyNumber: 26,
      constituencyName: "habiganj-1",
      homeAddress: "bahubal, habiganj",
      upazila: {
        upazilaName: "bahubal",
        unionName: "bahubal union",
        wardNumber: 8,
      },
    },
  },
  {
    _id: "y5u74x",
    voterId: "VOTER0025",
    voterName: "Nasir Uddin",
    dateOfBirth: "1991-05-05",
    constituency: {
      divisionName: "khulna",
      districtName: "bagerhat",
      constituencyNumber: 95,
      constituencyName: "bagerhat-2",
      homeAddress: "fakirhat, bagerhat",
      upazila: {
        upazilaName: "fakirhat",
        unionName: "fakirhat union",
        wardNumber: 5,
      },
    },
  },
  {
    _id: "z6v85y",
    voterId: "VOTER0026",
    voterName: "Rasheda Akter",
    dateOfBirth: "1980-12-01",
    constituency: {
      divisionName: "barisal",
      districtName: "jhalokati",
      constituencyNumber: 122,
      constituencyName: "jhalokati-2",
      homeAddress: "rajapur, jhalokati",
      upazila: {
        upazilaName: "rajapur",
        unionName: "rajapur union",
        wardNumber: 6,
      },
    },
  },
  {
    _id: "a7w96z",
    voterId: "VOTER0027",
    voterName: "Sabbir Rahman",
    dateOfBirth: "1995-06-16",
    constituency: {
      divisionName: "mymensingh",
      districtName: "netrokona",
      constituencyNumber: 149,
      constituencyName: "netrokona-3",
      homeAddress: "kendua, netrokona",
      upazila: {
        upazilaName: "kendua",
        unionName: "kendua union",
        wardNumber: 7,
      },
    },
  },
  {
    _id: "b8x07a",
    voterId: "VOTER0028",
    voterName: "Shamima Sultana",
    dateOfBirth: "1990-07-21",
    constituency: {
      divisionName: "rangpur",
      districtName: "kurigram",
      constituencyNumber: 132,
      constituencyName: "kurigram-2",
      homeAddress: "rowmari, kurigram",
      upazila: {
        upazilaName: "rowmari",
        unionName: "rowmari union",
        wardNumber: 2,
      },
    },
  },
  {
    _id: "c9y18b",
    voterId: "VOTER0029",
    voterName: "Tanvir Alam",
    dateOfBirth: "1998-09-27",
    constituency: {
      divisionName: "chattogram",
      districtName: "noakhali",
      constituencyNumber: 17,
      constituencyName: "noakhali-3",
      homeAddress: "begumganj, noakhali",
      upazila: {
        upazilaName: "begumganj",
        unionName: "begumganj union",
        wardNumber: 4,
      },
    },
  },
  {
    _id: "d0z29c",
    voterId: "VOTER0030",
    voterName: "Sharmin Akter",
    dateOfBirth: "1996-11-13",
    constituency: {
      divisionName: "sylhet",
      districtName: "sunamganj",
      constituencyNumber: 28,
      constituencyName: "sunamganj-1",
      homeAddress: "bishwamvarpur, sunamganj",
      upazila: {
        upazilaName: "bishwamvarpur",
        unionName: "bishwamvarpur union",
        wardNumber: 9,
      },
    },
  },
];
